dataset:
  proto: Multi30kDataset
  root: /home/zniu/workspace/dataset/multi30k
  src: de
  tgt: en

model:
  proto: Transformer

  encoder:
    proto: TransformerEncoder
    model_dim: 512
    ffn_dim: 2048
    layers: 6
    heads: 8
    input_dim: 19085 # de

  decoder:
    proto: TransformerDecoder
    model_dim: 512
    ffn_dim: 2048
    layers: 6
    heads: 8
    output_dim: 11174 # en

train:
  device: cuda
  lr: 0.001
  batch_size: 32
  epochs: 200
  continued: true
  save_every: 10

test:
  device: cuda
  batch_size: 1
  beam_width: 5
  splits: [val, test]
  max_len: 30
  all: false
