dataset:
  proto: XiaoshiDataset
  root: /home/zniu/workspace/dataset/xiaoshi
  src: org
  tgt: tra

model:
  proto: Transformer

  encoder:
    proto: TransformerEncoder
    model_dim: 512
    ffn_dim: 2048
    layers: 6
    heads: 8
    input_dim: 3553

  decoder:
    proto: TransformerDecoder
    model_dim: 512
    ffn_dim: 2048
    layers: 6
    heads: 8
    output_dim: 3705

train:
  device: cuda
  lr: 0.01
  batch_size: 8
  epochs: 100
  continued: true
  save_every: 5

test:
  device: cuda
  batch_size: 32
  beam_width: 20
  splits: [val, test]
  max_len: 50
  all: false
